config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "plants#index"
  resources :plants do
    member do
    post 'update_date'
    post 'update_agrochemical_date'
    end
  end

  resources :users, only: :show
end

app/models/agrochemical_time.rb
class AgrochemicalTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1ヶ月に一度は薬散' },
    { id: 3, name: '3ヶ月に一度は薬散' },
    { id: 4, name: '半年に一度は薬散（春・秋）' }
  ]

  include ActiveHash::Associations
  has_many :plants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/growth_time.rb
class GrowthTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '春・秋が成長期' },
    { id: 3, name: '夏が成長期' },
    { id: 4, name: '冬が成長期' }
  ]

  include ActiveHash::Associations
  has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord

  validates :plant_name,           presence: true, length: { minimum: 1, maximum: 20 }
  validates :plant_category,       presence: true, length: { minimum: 1, maximum: 20 }
  validates :watering_id,          presence: true, numericality: { other_than: 1 }
  validates :watering_day,         presence: true
  validates :growth_time_id,       presence: true, numericality: { other_than: 1 }
  validates :growth_day,           presence: true
  validates :agrochemical_time_id, presence: true, numericality: { other_than: 1 }
  validates :agrochemical_day,     presence: true
  validates :plant_text,           length: { minimum: 0, maximum: 1000 }

  belongs_to :user
  has_one_attached :image


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :watering
  belongs_to :growth_time
  belongs_to :agrochemical_time
end

app/models/region.rb
class Region < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,            presence: true
  validates :region_id,       presence: true, numericality: { other_than: 1 }
  validates :password,        format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }

  has_many :plants
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :region

end

app/models/watering.rb
class Watering < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '乾いたら水をあげる 2、3日に1回' },
    { id: 3, name: '多めの水をあげる 1日に1回' },
    { id: 4, name: '少なめの水やり 1週間に1回' }
  ]

  include ActiveHash::Associations
  has_many :plants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :region_id ])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:update_date, :update_agrochemical_date, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  before_action :move_to_index, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
    @plants = current_user.plants
    @today_watering = current_user.plants.where("watering_day = ? OR watering_day < ?", Date.today, Date.today).order(:watering_day)
    @next_watering = current_user.plants.where("watering_day > ?", Date.today).order(:watering_day)
    @today_agrochemical = current_user.plants.where("agrochemical_day = ? OR agrochemical_day < ?", Date.today, Date.today).order(:agrochemical_day)
    @next_agrochemical = current_user.plants.where("agrochemical_day > ?", Date.today).order(:agrochemical_day)
    @today_growth = current_user.plants.where(growth_day: Date.today)
    else
    end
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant =  Plant.create(plant_params)
    if @plant.save
    redirect_to root_path
    else
    render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
      if @plant.update(plant_params)
      redirect_to root_path
      else
      render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    @plant.destroy
    redirect_to root_path
  end

  def update_date
      if @plant.watering_id == 2
        @plant.update(watering_day: Date.today + 3.days)
      elsif @plant.watering_id == 3
        @plant.update(watering_day: Date.today + 1.day)
      elsif @plant.watering_id == 4
        @plant.update(watering_day: Date.today + 7.days)
      end
      redirect_to root_path
  end

  def update_agrochemical_date
    if @plant.agrochemical_time_id == 2
      @plant.update(agrochemical_day: Date.today + 30.days)
    elsif @plant.agrochemical_time_id == 3
      @plant.update(agrochemical_day: Date.today + 90.days)
    elsif @plant.agrochemical_time_id == 4
      if Date.today.month >= 12 || (Date.today.month >= 1 && Date.today.month <= 5)
        @plant.update(agrochemical_day: Date.new(Date.today.year, 3, 1))
      elsif Date.today.month >= 6 && Date.today.month <= 11
        @plant.update(agrochemical_day: Date.new(Date.today.year, 9, 1))
      end
    end
    redirect_to root_path
  end

  private

  def plant_params
    params.require(:plant).permit(:plant_name ,:plant_category ,:watering_id ,:watering_day ,:growth_time_id ,:growth_day ,:agrochemical_time_id ,:agrochemical_day ,:image ,:plant_text ,:start_time ,:plant_price).merge(user_id: current_user.id)
  end

  def set_plant
    @plant = Plant.find(params[:id])
  end

  def move_to_index
    return if current_user.id == @plant.user_id
    redirect_to action: :index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @plants = current_user.plants
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title>Botanical-Assist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: 'all',"data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "マイページ", "/users/#{current_user.id}", class: :nav__btn %>
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__btn %>
              <%= link_to "新規植物登録", new_plant_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path , class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Nan9.Botanical</p>
    </footer>
  </body>
</html>

app/views/plants/_agrochemical.html.erb
<div class="card">
  <% if plant.image.attached? %>
    <%= link_to image_tag(plant.image, class: :card__img ), plant_path(plant.id) %>
    <% else %>
    <%= link_to image_tag("/assets/noimage.jpg", class: :card__img), plant_path(plant.id) %>
  <% end %>
  <div class="card__body">
    <%= (plant.agrochemical_day).strftime("%Y/%m/%d") %>
  </div>
  <div class="card__title" >
    <% if plant.growth_time_id == 2 && ((Date.today.month >= 3 && Date.today.month <= 5) || (Date.today.month >= 10 && Date.today.month <= 11)) %>
    <%= "春・秋が成長期です。"%><br  />
    <% elsif plant.growth_time_id == 3 && (Date.today.month >= 6 && Date.today.month <= 9) %>
    <%= "夏が成長期です。"%><br  />
    <% elsif plant.growth_time_id == 4 && ((Date.today.month >= 11 && Date.today.month <= 12) || (Date.today.month >= 1 && Date.today.month <= 3)) %>
    <%= "冬が成長期です。"%><br  />
    <% end %>
    <%= "#{plant.plant_name}に<span style='color: red;'>薬散</span>をします。".html_safe %>
  </div>
    <%= button_to "薬散完了", update_agrochemical_date_plant_path(plant), class: :form__btn %>
</div>

app/views/plants/_form.html.erb
<%= form_with model: @plant, local: true do |f|%>

  <div class="field">
    <%= f.label :plant_name, "植物の名前" %><span class="indispensable">必須</span><br />
    <%= f.text_field :plant_name, id:"plant_name" %>
  </div>

  <div class="field">
    <%= f.label :plant_category, "植物の種類（学名、分類名等）" %><span class="indispensable">必須</span><br />
    <%= f.text_field :plant_category, id:"plant_category" %>
  </div>

  <div class="weight-bold-text">
    水やりの頻度
  <span class="indispensable">必須</span></div>
  <%= f.collection_select(:watering_id, Watering.all, :id, :name, {}, {class:"select-box", id:"watering-day"}) %>
  <%= f.date_select :watering_day, { use_month_numbers: true, use_short_month: true } %>

  <div class="weight-bold-text">
    成長の時期
  <span class="indispensable">必須</span></div>
  <%= f.collection_select(:growth_time_id, GrowthTime.all, :id, :name, {}, {class:"select-box", id:"growth-day"}) %>
  <%= f.date_select :growth_day, { use_month_numbers: true, use_short_month: true } %>

  <div class="weight-bold-text">
    薬散の時期
  <span class="indispensable">必須</span></div>
  <%= f.collection_select(:agrochemical_time_id, AgrochemicalTime.all, :id, :name, {}, {class:"select-box", id:"agrochemical-day"}) %>
  <%= f.date_select :agrochemical_day, { use_month_numbers: true, use_short_month: true } %>

  <div class="field">
    <%= f.label :image, "植物の写真" %><br />
    <%= f.file_field :image, id:"plant_image" %>
  </div>

  <div class="field">
    <%= f.label :plant_text, "備考（置き場等）" %><br />
    <%= f.text_area :plant_text, class: :form__text, id:"plant_text" %>
  </div>

  <div class="field">
    <%= f.label :plant_price, "値段" %><br />
    <%= f.text_field :plant_price, id:"plant_price" %>
  </div>

  <div class="field">
    <%= f.label :start_time, "購入日（管理開始日）" %><span class="indispensable">必須</span><br />
    <%= f.date_select :start_time, { use_month_numbers: true, use_short_month: true } %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/plants/_nextagrochemical.html.erb
 <div class="card">
  <div class="card__body">
    <%= (plant.agrochemical_day).strftime("%Y年%m月%d日") %><br  />
    <%= "#{plant.plant_name}の<span style='color: red;'>薬散</span>の予定です。".html_safe %>
  </div>
  <% if plant.image.attached? %>
   <%= link_to image_tag(plant.image, class: :card__img ), plant_path(plant.id) %>
  <% else %>
   <%= link_to image_tag("/assets/noimage.jpg", class: :card__img), plant_path(plant.id) %>
  <% end %>


</div>

app/views/plants/_nextwatering.html.erb
 <div class="card">
  <div class="card__body">
    <%= (plant.watering_day).strftime("%Y年%m月%d日") %><br  />
    <%= "#{plant.plant_name}に水をあげる予定です。"%>
  </div>
  <% if plant.image.attached? %>
   <%= link_to image_tag(plant.image, class: :card__img ), plant_path(plant.id) %>
  <% else %>
   <%= link_to image_tag("/assets/noimage.jpg", class: :card__img), plant_path(plant.id) %>
  <% end %>


</div>

app/views/plants/_plant.html.erb
<div class="card">
  <% if plant.image.attached? %>
    <%= link_to image_tag(plant.image, class: :card__img ), edit_plant_path(plant.id) %>
    <% else %>
    <%= link_to image_tag("/assets/noimage.jpg", class: :card__img), edit_plant_path(plant.id) %>
  <% end %>
  <div class="card__body">
    <%= link_to plant.plant_name, edit_plant_path(plant.id), class: :card__title%>
    <p class="card__category"><%= plant.plant_category %></p>
    <p class="card__category"><%= plant.plant_text %></p>
  </div>
</div>

app/views/plants/_watering.html.erb
<div class="card">
  <% if plant.image.attached? %>
    <%= link_to image_tag(plant.image, class: :card__img ), plant_path(plant.id) %>
    <% else %>
    <%= link_to image_tag("/assets/noimage.jpg", class: :card__img), plant_path(plant.id) %>
  <% end %>
  <div class="card__body">
    <%= (plant.watering_day).strftime("%Y/%m/%d") %>
  </div>
  <div class="card__title" >
    <% if plant.growth_time_id == 2 && ((Date.today.month >= 3 && Date.today.month <= 5) || (Date.today.month >= 10 && Date.today.month <= 11)) %>
    <%= "春・秋が成長期です。"%><br  />
    <% elsif plant.growth_time_id == 3 && (Date.today.month >= 6 && Date.today.month <= 9) %>
    <%= "夏が成長期です。"%><br  />
    <% elsif plant.growth_time_id == 4 && ((Date.today.month >= 11 && Date.today.month <= 12) || (Date.today.month >= 1 && Date.today.month <= 3)) %>
    <%= "冬が成長期です。"%><br  />
    <% end %>
    <%= "#{plant.plant_name}に<span style='color: blue;'>水</span>をあげます。".html_safe %>
  </div>
    <%= button_to "潅水完了", update_date_plant_path(plant), class: :form__btn %>
</div>

app/views/plants/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">植物情報の編集</h2>
      <%= render partial: "form", locals: { plant: @plant } %>
    </div>
    <div class="actions">
    <%= link_to "削除する", plant_path(@plant.id),data: { turbo_method: :delete , turbo_confirm: "本当に削除しますか？" }, class: :form__btn %>
    </div>
  </div>
</div>

app/views/plants/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to current_user.name, edit_user_registration_path(current_user.id), class: :greeting__link%>
        さん
      </div>
      <% if @plants.any? %>
        <% if @today_watering.any? || @today_agrochemical.any?%>
          <h1><%=Date.today.strftime("%Y年%m月%d日")%> の作業内容は</h1>
          <div class="card__wrapper">
            <% @today_watering.each do |plant| %>
              <%= render partial: "watering", locals:{plant: plant} %>
            <% end %>
            <% @today_agrochemical.each do |plant| %>
              <%= render partial: "agrochemical", locals:{plant: plant} %>
            <% end %>
          </div>
        <% else %>
          <div class="finish_text">
            今日の予定は完了しました。
          </div>
          <h2>これからの予定は</h2>
          <div class="card__wrapper">
            <% @next_watering.each do |plant| %>
            <%= render partial: "nextwatering", locals:{plant: plant} %>
            <% end %>
            <% @next_agrochemical.each do |plant| %>
            <%= render partial: "nextagrochemical", locals:{plant: plant} %>
            <% end %>
          </div>
          <% end %>
      <% else %>
        <h1>どんな植物を育ててますか？<br>植物を登録しましょう。</h1>
      <% end %>
      <% else %>
      <div>「部屋に緑が欲しいけど、育てることができるだろうか…」<br>
      植物を育てるのは、難しくてどうしても枯らしてしまう…」<br>
      そんな悩みを解決します。<br>
      <br>
      Botanical-Assistは<br>
      植物を管理するうえで必要なタスクを適切なタイミングで行うことを<br>
      サポートします。
      </div>
        <a><img src="https://i.gyazo.com/daad4f8a2274dbeff31a9de8bb3a7c37.jpg" alt="Image from Gyazo" class="card__img"/></a>
    <% end %>
  </div>
</main>

app/views/plants/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新しい植物の情報</h2>
        <%= render partial: "form", locals: { plant: @plant } %>
    </div>
  </div>
</div>

app/views/plants/show.html.erb
<main class="main">
  <div class="inner">
    <div class="plant__wrapper">
      <p class="plant__hedding">
      <%= @plant.plant_name %>
      </p>
        <div class="plant__manage">
        <%= link_to "編集する", edit_plant_path(@plant.id), class: :form__btn %>
        </div>
        <% if @plant.image.attached? %>
        <div class="plant__image">
        <%= link_to image_tag(@plant.image, class: :card__img ), edit_plant_path(@plant.id) %>
        <% else %>
        <%= link_to image_tag("/assets/noimage.jpg", class: :card__img), edit_plant_path(@plant.id) %>
        </div>
        <% end %>
        </div>
      <div class="plant__body">
        <div class="plant__detail">
          <p class="detail__title">植物名</p>
          <p class="detail__message">
            <%= @plant.plant_name %>
          </p>
        </div>
        <div class="plant__detail">
          <p class="detail__title">購入日</p>
          <p class="detail__message">
            <%= @plant.start_time.strftime("%Y年%m月%d日") %>
          </p>
        </div>
        <div class="plant__detail">
          <p class="detail__title">値段</p>
          <p class="detail__message">
            <%= @plant.plant_price %>円
          </p>
        </div>
        <div class="plant__detail">
          <p class="detail__title">備考</p>
          <p class="detail__message">
            <% if @plant.plant_text = nil%>
            <%= @plant.plant_text %>
            <% else %>
            <%= "無し" %>
            <% end %>
          </p>
        </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{current_user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= current_user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">地域</th>
            <td class="table__col2"><%= current_user.region.name %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{current_user.name}さんの持っている植物"%>
      </h2>
      <div class="user__card">
          <% @plants.each do |plant| %>
          <%= render partial: "plants/plant", locals: { plant: plant } %>
          <% end %>
      </div>
    </div>
  </div>
</div>